import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, Enum, Numeric, String, Text
from sqlalchemy import UUID as SAUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UserScopedMixin
from app.db.enums import DirectionType, OutcomeType, TradeStatus

# --------------------------------------------------------------------------
# TRADE COHORTS — which rows may be presented as live performance
#
# `setup_tag` separates genuine live paper trades from injected backtest-replay
# rows. Getting this wrong is not cosmetic: the replay rows currently in
# production were generated by the PRE-FIX engine and average +0.081R, while the
# corrected engine averages -0.118R. Folding them into a performance view
# displays a profitable track record that the strategy has never had.
#
# These constants exist because the literal "Backtest replay" was previously
# repeated across six call sites. A tag renamed in one place would have silently
# stopped matching in the others — and the failure mode is a filter that quietly
# passes everything, which looks exactly like a filter that works.
# --------------------------------------------------------------------------

#: Injected backtest rows. NEVER counts as live performance.
SETUP_TAG_REPLAY = "Backtest replay"

#: Genuine live paper trades, written by the live loop's settle hook.
SETUP_TAG_LIVE = "ICT (live)"


def is_live_cohort(setup_tag: str | None) -> bool:
    """True if a row may be presented as live performance.

    An untagged row counts as LIVE. That is deliberate: replay rows are always
    written with an explicit tag, so anything untagged came from a real trading
    path. Defaulting the unknown case to "replay" would hide real trades, which
    is the more dangerous error — a missing loss is worse than a visible one.
    """
    return setup_tag != SETUP_TAG_REPLAY


# --------------------------------------------------------------------------
# EXIT MODES — the loop's mode when an exit was DECIDED (`T-0146` REVISIONS 3–4)
#
# Written to `trades.exit_mode` (migration `0018`). It is the mode at the
# DECISION, never re-read by a retried settle write. NULL means a row from
# before `0018` or a simulator trade. `UNRECORDED` is a settle from FILLs of an
# engine close whose hint is missing or has no mode — never `RUNNING`. `0018`
# freezes these five as `_EXIT_MODES_AT_0018`; an arm holds the two equal.
# --------------------------------------------------------------------------

EXIT_MODE_RUNNING = "RUNNING"
EXIT_MODE_MANAGE_ONLY = "MANAGE_ONLY"
#: A person's Stop-button close (leg `x`).
EXIT_MODE_STOPPING = "STOPPING"
#: An exit the engine did not send (the kill switch, a manual close), settled from FILLs.
EXIT_MODE_EXTERNAL = "EXTERNAL"
EXIT_MODE_UNRECORDED = "UNRECORDED"

EXIT_MODES: tuple[str, ...] = (
    EXIT_MODE_RUNNING,
    EXIT_MODE_MANAGE_ONLY,
    EXIT_MODE_STOPPING,
    EXIT_MODE_EXTERNAL,
    EXIT_MODE_UNRECORDED,
)


class Trade(UserScopedMixin, TimestampMixin, Base):
    __tablename__ = "trades"

    id: Mapped[uuid.UUID] = mapped_column(
        SAUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    broker_id: Mapped[str] = mapped_column(String, nullable=False)
    broker: Mapped[str] = mapped_column(String, nullable=False)
    pair: Mapped[str] = mapped_column(String, nullable=False)
    direction: Mapped[DirectionType] = mapped_column(
        Enum(DirectionType, name="direction_t"),
        nullable=False,
    )
    entry_price: Mapped[Decimal] = mapped_column(Numeric(18, 6), nullable=False)
    exit_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)
    sl: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)
    tp: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)
    #: A QUANTITY, so 9 dp (`B458`, migration `0017`): the venue's quantity grid is `1e-9`, and 6 dp
    #: rounded a crypto lot like `0.000058413` to `0.000058`. The prices around it stay at 6 dp.
    lot_size: Mapped[Decimal] = mapped_column(Numeric(21, 9), nullable=False)
    entry_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    exit_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r_multiple: Mapped[Decimal | None] = mapped_column(Numeric(8, 2), nullable=True)
    outcome: Mapped[OutcomeType] = mapped_column(
        Enum(OutcomeType, name="outcome_t"),
        nullable=False,
        default=OutcomeType.OPEN,
    )
    session: Mapped[str | None] = mapped_column(String, nullable=True)
    status: Mapped[TradeStatus] = mapped_column(
        Enum(TradeStatus, name="trade_status_t"),
        nullable=False,
        default=TradeStatus.OPEN,
    )
    pnl_dollars: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    pnl_pips: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Which engine run produced this trade. Lets a reset scope metrics to the
    #: new run without deleting anything — see models/engine_run.py.
    run_id: Mapped[uuid.UUID | None] = mapped_column(
        SAUUID(as_uuid=True), nullable=True, index=True
    )
    setup_tag: Mapped[str | None] = mapped_column(String, nullable=True)
    #: The ENGINE close order's client id (`T-0144` I-1, migration `0018`): `tai-<32 hex>-<leg><2-digit
    #: attempt>`, 40 characters. "Partial taken" is read from this identity (leg `p`), never from a size.
    #: NULL for simulator trades and external exits — no engine close id exists, and none is fabricated.
    close_client_order_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    #: One of `EXIT_MODES`, the mode when the exit was DECIDED (migration `0018`). NULL = a row from before
    #: `0018` or a simulator trade. No default: a forgotten write must read as unknown, not as `RUNNING`.
    exit_mode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    #: P-4 / R3' (migration `0018`): the mark the pass compared with the level when it DECIDED the exit, from the
    #: `SettleEvent` — never re-read at persist time. A USD price, so 6 dp like the prices above. Slippages are
    #: DERIVED, not stored: detection = mark − the triggering level (`sl` for a stop exit), execution =
    #: `exit_price` − mark. NULL for simulator trades.
    mark_at_detection: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)
    #: The feed that mark came from (e.g. `binance_mark`). NULL for simulator trades.
    mark_source: Mapped[str | None] = mapped_column(String(32), nullable=True)
    #: R1': the MEASURED wall time of the pass that detected the exit (`_last_pass_s`), not `POLL_INTERVAL`.
    #: NULL for simulator trades.
    detection_interval_s: Mapped[Decimal | None] = mapped_column(Numeric(10, 3), nullable=True)

    # Relationships
    screenshots: Mapped[list["Screenshot"]] = relationship(  # noqa: F821
        "Screenshot", back_populates="trade", lazy="select"
    )
    checklists: Mapped[list["Checklist"]] = relationship(  # noqa: F821
        "Checklist", back_populates="trade", lazy="select"
    )
    orders: Mapped[list["Order"]] = relationship(  # noqa: F821
        "Order", back_populates="trade", lazy="select"
    )
