"""/api/trades must not hand back replay rows to a caller asking for performance.

This pins the fix for a defect that was live in production: the report page drew
a RISING equity curve over 247 rows -- 245 of them injected backtest replay --
directly beside a headline that correctly read "2 closed trades / -$880". The
dashboard chart had the same bug, drawing markers for trades the account never
took.

Worse, those replay rows were generated by the PRE-FIX engine: they average
+0.081R, while the corrected engine averages -0.118R. So the curve was not merely
mixing cohorts, it was displaying the discredited lookahead-inflated result that
this entire project exists to have stopped believing.

The endpoint therefore defaults to the live cohort. These tests fail if that
default is ever flipped back.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from decimal import Decimal

import pytest

from app.db.enums import DirectionType, OutcomeType, TradeStatus
from app.api.deps import _SINGLE_USER_ID
from app.models.trade import SETUP_TAG_LIVE, SETUP_TAG_REPLAY, Trade, is_live_cohort


def _trade(user_id: str, setup_tag: str | None, pnl: float, pair: str = "BTC/USD") -> Trade:
    now = datetime.now(timezone.utc)
    return Trade(
        user_id=user_id, broker_id="paper", broker="paper", pair=pair,
        direction=DirectionType.LONG,
        entry_price=Decimal("100"), exit_price=Decimal("101"), lot_size=Decimal("1"),
        entry_time=now - timedelta(hours=1), exit_time=now,
        outcome=OutcomeType.WIN if pnl > 0 else OutcomeType.LOSS,
        status=TradeStatus.CLOSED, pnl_dollars=Decimal(str(pnl)), setup_tag=setup_tag,
    )


@pytest.fixture
async def seeded(db_session):
    """Two replay rows, one tagged-live row, one untagged row."""
    db_session.add_all([
        _trade(_SINGLE_USER_ID, SETUP_TAG_REPLAY, 500.0),
        _trade(_SINGLE_USER_ID, SETUP_TAG_REPLAY, 400.0),
        _trade(_SINGLE_USER_ID, SETUP_TAG_LIVE, -300.0),
        _trade(_SINGLE_USER_ID, None, -80.0),          # untagged == live
    ])
    await db_session.commit()


async def _tags(client, query: str) -> list[str | None]:
    resp = await client.get(f"/api/trades{query}")
    assert resp.status_code == 200, resp.text
    return [t["setup_tag"] for t in resp.json()]


# ---------------------------------------------------------------------------
# The default is the whole point
# ---------------------------------------------------------------------------
async def test_default_excludes_replay(seeded, client):
    """No cohort param at all -- a naive caller must still get honest data."""
    tags = await _tags(client, "?page_size=500")
    assert SETUP_TAG_REPLAY not in tags, (
        "the DEFAULT response contains backtest-replay rows; any caller that "
        "forgets ?cohort=live will present them as live performance"
    )
    assert len(tags) == 2
    assert all(is_live_cohort(t) for t in tags)


async def test_untagged_rows_count_as_live(seeded, client):
    """NULL setup_tag is a real trade, not an unknown to be filtered away.

    Guards the SQL trap specifically: `setup_tag != 'Backtest replay'` evaluates
    to NULL (not TRUE) for untagged rows, so a naive `!=` silently drops every
    real trade written without a tag. The query must use IS DISTINCT FROM.
    """
    tags = await _tags(client, "?cohort=live&page_size=500")
    assert None in tags, "an untagged live trade was dropped by the cohort filter"


# ---------------------------------------------------------------------------
# The other cohorts remain reachable
# ---------------------------------------------------------------------------
async def test_explicit_live_matches_default(seeded, client):
    assert await _tags(client, "?cohort=live&page_size=500") == await _tags(client, "?page_size=500")


async def test_all_returns_every_row(seeded, client):
    tags = await _tags(client, "?cohort=all&page_size=500")
    assert len(tags) == 4, "the journal needs the full ledger via cohort=all"
    assert tags.count(SETUP_TAG_REPLAY) == 2


async def test_replay_cohort_isolates_replay(seeded, client):
    tags = await _tags(client, "?cohort=replay&page_size=500")
    assert tags == [SETUP_TAG_REPLAY, SETUP_TAG_REPLAY]


async def test_invalid_cohort_is_rejected(seeded, client):
    resp = await client.get("/api/trades?cohort=everything")
    assert resp.status_code == 422, "an unknown cohort must fail loudly, not fall back"


# ---------------------------------------------------------------------------
# Composition with the other filters
# ---------------------------------------------------------------------------
async def test_cohort_composes_with_pair_filter(db_session, client):
    db_session.add_all([
        _trade(_SINGLE_USER_ID, SETUP_TAG_REPLAY, 500.0, pair="ETH/USD"),
        _trade(_SINGLE_USER_ID, SETUP_TAG_LIVE, -20.0, pair="ETH/USD"),
        _trade(_SINGLE_USER_ID, SETUP_TAG_LIVE, -30.0, pair="BTC/USD"),
    ])
    await db_session.commit()

    tags = await _tags(client, "?pair=ETH/USD&page_size=500")
    assert tags == [SETUP_TAG_LIVE], "cohort and pair filters must both apply"


# ---------------------------------------------------------------------------
# The constant itself
# ---------------------------------------------------------------------------
def test_is_live_cohort_classifies_correctly():
    assert is_live_cohort(None) is True
    assert is_live_cohort(SETUP_TAG_LIVE) is True
    assert is_live_cohort("anything else") is True
    assert is_live_cohort(SETUP_TAG_REPLAY) is False
