"""decision_records — every engine decision (trade or abstain).

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-17 00:00:00.000000

Hand-written (NOT autogenerated). Enum-like columns are modelled as
sa.String + a CHECK constraint so NO new PostgreSQL ENUM type is created.

The CHECK vocabularies and the column set are imported from the ORM model
(app.models.decision_record) so this migration can never silently drift from
the table the application actually maps. That drift was the exact defect an
earlier draft shipped (outcome CHECK missing ABSTAINED, no cohort CHECK).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

#: **FROZEN (`B405`/`B416`). THE THREE VOCABULARIES THIS REVISION ACTUALLY CREATED**, written out
#: rather than imported from the live model.
#:
#: **THIS IS NOT A PRECAUTION — IT WAS ALREADY WRONG.** The outcome list holds eight values now
#: (`ABANDONED` joined at `0006`, `REJECTED` at `0008`, `UNSIZED_FILL` at `0013`), so replaying this
#: revision on a fresh database created a CHECK admitting all of them where production's `0002`
#: admitted five. The end states coincide only because later revisions widen it anyway; a database
#: stopped at `0002` had a vocabulary production never had at `0002`.
#:
#: **WHERE THE FIVE COMES FROM, and the justification moved twice while the value never did.**
#: All three steps are written out because each was believed, and the first two were each one step
#: short in a file whose whole purpose is to be trusted without re-derivation.
#:
#: **`0002` HAD TWO LIVES**, which is why this file is the only one of the four where reading the
#: model and reading the migration disagree:
#:
#: ```
#: 2580ffe  2026-07-19 22:40  LITERAL: outcome IN ('WIN','LOSS','BE','OPEN')   FOUR, no ABSTAINED,
#:                            no IS NULL OR, and NO cohort CHECK — only an index
#: 8fdaf6a  2026-07-19 22:54  rewritten to IMPORT the model, and to create ck_decision_records_cohort
#: ```
#:
#: ```
#: STEP 1  the model at 0002's landing commit said five
#:         -> RIGHT BY LUCK, and it is `B405`'s own method: reading a migration's historical
#:            constraint off the MODEL instead of off the MIGRATION. At that commit this file
#:            held a literal and read no model at all.
#: STEP 2  ck_decision_records_cohort is present in production, so the REWRITTEN 0002 ran
#:         -> ONE STEP SHORT, and worse than step 1 because it reads as a measurement rather than
#:            as a derivation. The rewritten 0002 is precisely the file that builds its CHECK at
#:            RUN TIME from whatever the model holds that day — which is the entire reason it
#:            needed freezing. "It ran" is compatible with it having written six.
#: STEP 3  0002 CREATES the table, so the first row bounds when it ran:
#:              min(created_at) in decision_records   2026-07-22 04:00:09   (1678 rows)
#:              ABANDONED joins the model at 0006     2026-08-09 19:43
#:              corroboration: earliest engine_run    2026-08-04 00:43:12
#:         -> EIGHTEEN DAYS EARLIER. 0002 ran while the model held FIVE. CLOSED.
#: ```
#:
#: **STEP 3's OWN PREMISE WAS CHECKED RATHER THAN ASSUMED:** the bound holds only if that timestamp
#: is server-generated. `created_at` is `server_default=func.now()` in the model, `now()` in the
#: deployed schema, and no writer in `backend/app` passes `created_at=`. A client-supplied value
#: could have been backdated and the inequality would have proved nothing — failing in the
#: reassuring direction.
#:
_OUTCOMES_AT_0002: tuple[str, ...] = ("WIN", "LOSS", "BE", "OPEN", "ABSTAINED")
_COHORTS_AT_0002: tuple[str, ...] = ("replay", "backtest", "paper", "live")
_DIRECTIONS_AT_0002: tuple[str, ...] = ("LONG", "SHORT")


def _sql_in(column: str, values: tuple[str, ...]) -> str:
    """Copied from the model as it stood at `2580ffe`, for the reason above."""
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({quoted})"


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # One row per engine decision — trade signal OR abstain. Enum-like columns
    # (signal_dir, outcome, cohort) use sa.String + a CHECK built from the same
    # module constants the ORM model uses, so DDL and ORM can't diverge. No new
    # PG ENUM type is created. A NULL operand makes a CHECK UNKNOWN, which
    # PostgreSQL treats as satisfied — nullable enum-like columns still accept
    # NULL, and we spell that out explicitly for portability.
    op.create_table(
        "decision_records",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("inputs_hash", sa.String(), nullable=False),
        sa.Column("code_path_hash", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=False, server_default="FALSE"),
        sa.Column("reasons", sa.JSON(), nullable=True),
        sa.Column("signal_dir", sa.String(), nullable=True),
        sa.Column("signal_entry", sa.Numeric(18, 6), nullable=True),
        sa.Column("signal_sl", sa.Numeric(18, 6), nullable=True),
        sa.Column("signal_tp", sa.Numeric(18, 6), nullable=True),
        sa.Column("sized_units", sa.Numeric(18, 6), nullable=True),
        sa.Column("expected_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("realized_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("gap_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("correction_json", sa.Text(), nullable=True),
        sa.Column("cohort", sa.String(), nullable=False, server_default="replay"),
        sa.CheckConstraint(
            f"signal_dir IS NULL OR {_sql_in('signal_dir', _DIRECTIONS_AT_0002)}",
            name="ck_decision_records_signal_dir",
        ),
        sa.CheckConstraint(
            f"outcome IS NULL OR {_sql_in('outcome', _OUTCOMES_AT_0002)}",
            name="ck_decision_records_outcome",
        ),
        sa.CheckConstraint(
            _sql_in("cohort", _COHORTS_AT_0002),
            name="ck_decision_records_cohort",
        ),
    )
    op.create_index(
        "ix_decision_records_created_at", "decision_records", ["created_at"]
    )
    op.create_index("ix_decision_records_cohort", "decision_records", ["cohort"])


def downgrade() -> None:
    op.drop_index("ix_decision_records_cohort", table_name="decision_records")
    op.drop_index("ix_decision_records_created_at", table_name="decision_records")
    op.drop_table("decision_records")
