"""decision_records — every engine decision (trade or abstain).

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-17 00:00:00.000000

Hand-written (NOT autogenerated). Enum-like columns are modelled as
sa.String + a CHECK constraint so NO new PostgreSQL ENUM type is created.

The CHECK vocabularies and the column set are imported from the ORM model
(app.models.decision_record) so this migration can never silently drift from
the table the application actually maps. That drift was the exact defect an
earlier draft shipped (outcome CHECK missing ABSTAINED, no cohort CHECK).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models.decision_record import (
    DECISION_COHORTS,
    DECISION_OUTCOMES,
    SIGNAL_DIRECTIONS,
    _sql_in,
)

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # One row per engine decision — trade signal OR abstain. Enum-like columns
    # (signal_dir, outcome, cohort) use sa.String + a CHECK built from the same
    # module constants the ORM model uses, so DDL and ORM can't diverge. No new
    # PG ENUM type is created. A NULL operand makes a CHECK UNKNOWN, which
    # PostgreSQL treats as satisfied — nullable enum-like columns still accept
    # NULL, and we spell that out explicitly for portability.
    op.create_table(
        "decision_records",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("inputs_hash", sa.String(), nullable=False),
        sa.Column("code_path_hash", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=False, server_default="FALSE"),
        sa.Column("reasons", sa.JSON(), nullable=True),
        sa.Column("signal_dir", sa.String(), nullable=True),
        sa.Column("signal_entry", sa.Numeric(18, 6), nullable=True),
        sa.Column("signal_sl", sa.Numeric(18, 6), nullable=True),
        sa.Column("signal_tp", sa.Numeric(18, 6), nullable=True),
        sa.Column("sized_units", sa.Numeric(18, 6), nullable=True),
        sa.Column("expected_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("realized_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("gap_r", sa.Numeric(12, 4), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("correction_json", sa.Text(), nullable=True),
        sa.Column("cohort", sa.String(), nullable=False, server_default="replay"),
        sa.CheckConstraint(
            f"signal_dir IS NULL OR {_sql_in('signal_dir', SIGNAL_DIRECTIONS)}",
            name="ck_decision_records_signal_dir",
        ),
        sa.CheckConstraint(
            f"outcome IS NULL OR {_sql_in('outcome', DECISION_OUTCOMES)}",
            name="ck_decision_records_outcome",
        ),
        sa.CheckConstraint(
            _sql_in("cohort", DECISION_COHORTS),
            name="ck_decision_records_cohort",
        ),
    )
    op.create_index(
        "ix_decision_records_created_at", "decision_records", ["created_at"]
    )
    op.create_index("ix_decision_records_cohort", "decision_records", ["cohort"])


def downgrade() -> None:
    op.drop_index("ix_decision_records_cohort", table_name="decision_records")
    op.drop_index("ix_decision_records_created_at", table_name="decision_records")
    op.drop_table("decision_records")
