import json, pathlib
from decimal import Decimal
S = pathlib.Path("./_work"); OUT = pathlib.Path("./runs")
idx = json.load(open(S / "index.json")); d = json.load(open(S / "runs.json"))
TS = "2026-08-25T18:11:09Z"; tot = d["db_totals"]
tp = sum(Decimal(str(i["pnl"])) for i in idx)
import collections
_c = collections.Counter(json.dumps(r.get("config"), sort_keys=True) for r in d["runs"] if r.get("config"))
MODAL_JSON = json.dumps(json.loads(_c.most_common(1)[0][0]), indent=2) if _c else "(none recorded)"

L = [f"""# Engine runs — full record

**Every simulated run the engine has performed, exported from the production database.** One
document per run, plus the underlying rows in machine-readable form.

**Exported {TS}.** This is a point-in-time export, not a live view — see [METHOD.md](METHOD.md)
for how it was produced and what it does not contain.

## Why this exists

The register (`KNOWN_ISSUES.md`) cites figures from specific runs — `B268` quotes two runs by id,
`B277` and `B278` quote individual trades to six decimal places, `B215`'s closure quotes a live
position payload. **Until this export, none of that was reproducible without database access.**
These documents are what those claims rest on.

## Totals at export

| | |
|---|---|
| runs | **{tot['runs']}** |
| decision records | **{tot['decisions']}** |
| trade rows | **{tot['trades']}** |
| telemetry records | {tot['telemetry']} |
| candles | {tot['candles']} |

**DO NOT read a single P&L figure off this table.** Of the {tot['trades']} trade rows,
**249 belong to Run 01, and 245 of those are `setup_tag = "Backtest replay"`** — imported history,
not engine simulation. Separated:

| | rows | realised P&L |
|---|---|---|
| **Live engine simulation** (runs 02-24) | **34** | **807.96** |
| Run 01 — backtest replay + pre-run history | 249 | 21654.23 |

**The engine's own simulated trading has produced 807.96 across 34 trade rows.** The larger number
is replay data swept into a synthetic container run, and reporting the two together would overstate
live results by roughly twenty-seven times.

**Every decision record and every trade row maps to a real run** — measured: zero `NULL` run ids,
zero ids absent from `engine_runs`.

## The runs

Trades and positions differ: `EXIT-001` splits a position into a 70/30 pair, so one position can
produce two trade rows sharing a `broker_id` (`B225`).

| # | run | started | duration | decisions | abstained | signals | trades | positions | P&L |
|---|---|---|---|---|---|---|---|---|---|
"""]
for i in idx:
    L.append(f"| {i['n']:02d} | [`{i['short']}`]({i['slug']}.md) | `{i['started']}` | {i['dur']} "
             f"| {i['dec']} | {i['abst']} | {i['entries']} | {i['trades']} | {i['positions']} "
             f"| {i['pnl']} |\n")

L.append(f"""
## Three things to read before using the table

**Run 01 is not a real run.** Its id is `00000000-0000-0000-0000-000000000001` and its own note
says so: *"Everything recorded before runs existed. Left ACTIVE so the engine adopts it on first
start and no history disappears."* It is a container for pre-run history, it has no configuration
recorded, and **245 of its 249 trades are tagged `Backtest replay`** — only 4 are live. Its figures
are neither one session nor one kind of activity.

**The `positions` column is meaningless for Run 01, and that is `B225`.** All 249 of its trade rows
carry the literal `broker_id = "paper"`, because `broker_id` was written as a constant before the
fix. Grouping by it therefore reports **one** position for 249 trades. Every other run has real
per-position ids (5 distinct across runs 02-24), so the column means what it says from Run 02
onward.

**The last run had not ended when this was exported.** Its `ended_at` is null and its figures are
in flight; every other run is closed.

## Configuration

Runs record a config snapshot at start, so a result can never be read against the wrong settings.
The common configuration across runs that have one:

```json
{MODAL_JSON}
```

Each run document names how its own configuration differs from that, or states that it is identical.

## Machine-readable

* `data/decisions-<run>.jsonl` — **every** decision row for that run, all 24 columns, one JSON
  object per line. Nothing is summarised away.
* `data/trades.csv` — all {tot['trades']} trade rows across every run, all columns.

*Generated by a script over a single database extract; the script is not committed because it
embeds a connection. [METHOD.md](METHOD.md) states exactly what it did.*
""")
(OUT / "README.md").write_text("".join(L), encoding="utf-8")
print("README.md written")
